apiVersion: v1
kind: Namespace
metadata:
  name: coder-workspaces
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  labels:
    app.kubernetes.io/name: coder-workspaces
    app.kubernetes.io/part-of: coder
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
