apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: loky-planner
spec:
  networkRouterRef:
    name: homelab-services
    namespace: netbird
  serviceRef:
    name: loky-planner
  groups:
    - name: dashboard-services
