apiVersion: v1alpha1
kind: HostnameConfig
hostname: controlplane-2
---
apiVersion: v1alpha1
kind: LinkConfig
name: eno2
up: true
addresses:
    - address: 192.168.187.202/24
routes:
    - gateway: 192.168.187.1
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 192.168.187.200
link: eno2
