apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: homepage
  namespace: homepage
spec:
  networkRouterRef:
    name: homelab-services
    namespace: netbird
  serviceRef:
    name: homepage
  groups:
    - name: dashboard-services
