apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificates.yaml
  - network.yaml
  - network-policy.yaml
  - service-account.yaml
  - services.yaml
  - statefulset.yaml

configMapGenerator:
  - name: zot-config
    namespace: registry
    files:
      - config.json

labels:
  - pairs:
      app.kubernetes.io/part-of: container-registry
