apiVersion: v1
kind: ServiceAccount
metadata:
  name: zot
  namespace: registry
  labels:
    app.kubernetes.io/name: zot
    app.kubernetes.io/component: registry
automountServiceAccountToken: false
