apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: headlamp
  namespace: headlamp
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/component: network-access
spec:
  networkRouterRef:
    name: homelab-services
    namespace: netbird
  serviceRef:
    name: headlamp
  groups:
    - name: dashboard-services
