apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: caddy-system

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: caddy-config
    files:
      - Caddyfile
    options:
      labels:
        app.kubernetes.io/name: caddy
        app.kubernetes.io/component: reverse-proxy
