apiVersion: v1
kind: Service
metadata:
  name: caddy
  labels:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/component: reverse-proxy
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: caddy
  ports:
    - name: homepage
      port: 80
      targetPort: homepage
      protocol: TCP
      nodePort: 30080
    - name: argocd
      port: 8081
      targetPort: argocd
      protocol: TCP
      nodePort: 30081
    - name: longhorn
      port: 8082
      targetPort: longhorn
      protocol: TCP
      nodePort: 30082
    - name: hubble
      port: 8083
      targetPort: hubble
      protocol: TCP
      nodePort: 30083
    - name: grafana
      port: 8084
      targetPort: grafana
      protocol: TCP
      nodePort: 30084
    - name: prometheus
      port: 8085
      targetPort: prometheus
      protocol: TCP
      nodePort: 30085
    - name: alertmanager
      port: 8086
      targetPort: alertmanager
      protocol: TCP
      nodePort: 30086
    - name: minio
      port: 8087
      targetPort: minio
      protocol: TCP
      nodePort: 30087
